### PR TITLE
A few fixes while you're at the gym

### PR DESCRIPTION
**Pull request by rgbkrk**
We'll see how far I get. The nice thing about me making PRs to your refactor is that you can review it inline. :wink:

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm really glad you wrapped these up in distinct `build:js:*`. We could get them to work in little chunks first. None of them on their own finish a full bundling, but they're getting there!

**Comment by rgbkrk** [comment]
Bringing jquery in from npm works nicely. :smile:

Now I'm getting errors related to finding some of the notebook js itself `./login_main` and `contents`.

I'm not seeing termjs on npm though.

**Comment by rgbkrk** [comment]
Ok, I've got to run to a team dinner.

> It's dangerous to go alone. Take these commits.

**Comment by jdfreder** [comment]
Thanks man, this is great!

**Comment by rgbkrk** [comment]
I just realized I should have pinned jquery to the version we have pinned on bower. Should be fine, but it's something of note.

**Comment by jdfreder** [comment]
Actually, in the interest of saving us having it in two places, in the current PR I'm allowing browserify to import it from bower as opposed to npm.

**Comment by rgbkrk** [comment]
Totes cool, that makes sense.

Maybe it makes more sense to use the external option for bundling, exposing e.g. Jquery as a separate script tag, etc

**Comment by jdfreder** [comment]
I ended up using your jquery : )

**Pull request merged**
